apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: titan-fintech
spec:
  selector:
    app: payment-service # Must match the Deployment label
  ports:
    - protocol: TCP
      port: 80       # Port the Service exposes
      targetPort: 80 # Port the Container listens on
  type: ClusterIP    # Internal only